// keywords.js -- the keyword table and its synonyms.
//
// Edit the emoji here by copy/paste, never by retyping: multi-codepoint
// emoji (ZWJ sequences like the astronaut, variation selectors like the
// spider) look identical in an editor when retyped wrong and render as
// broken boxes in the browser.

// Every keyword in one place: the word, the background tint it fades the
// screen to, and the emoji that fill the grid behind it. One record per
// entry rather than three index-parallel arrays - adding, removing or
// reordering a keyword is a single line, and there is no way for the three
// fields to drift out of alignment with each other.
//
// Matching is on whole words, so "cat" never fires inside "catch", and
// plural/-ing forms are derived at match time (see matching.js) rather than
// listed here.
const keywords = [
    // -- shapes --
    {name: "circle", bg: '#134842', emoji: ["⚫", "⚪", "🔴", "🟢", "🔵"]},
    {name: "square", bg: '#102793', emoji: ["⬛", "⬜", "🟥", "🟩", "🟦"]},
    {name: "triangle", bg: '#f3d291', emoji: ["🔺", "🔻"]},
    {name: "diamond", bg: '#d3edf8', emoji: ["🔶", "🔷", "🔸", "🔹"]},
    {name: "heart", bg: '#7e1112', emoji: ["❤️", "🧡", "💛", "💚", "💙", "💜"]},
    // -- animals --
    {name: "cow", bg: '#684d27', emoji: ["🐄", "🐮"]},
    {name: "pig", bg: '#ae1338', emoji: ["🐖", "🐷", "🐽"]},
    {name: "horse", bg: '#e9985d', emoji: ["🐴", "🐎"]},
    {name: "ox", bg: '#cf7736', emoji: ["🐂"]},
    {name: "cat", bg: '#61360f', emoji: ["🐱", "🐈", "🐾"]},
    {name: "dog", bg: '#815336', emoji: ["🐶", "🐕", "🦴"]},
    {name: "donkey", bg: '#e9985d', emoji: ["🫏"]},
    {name: "goat", bg: '#50462b', emoji: ["🐐"]},
    {name: "sheep", bg: '#7a6629', emoji: ["🐑"]},
    {name: "chick", bg: '#81690e', emoji: ["🐤","🐥","🐣"]},
    {name: "chicken", bg: '#946119', emoji: ["🐔"]},
    {name: "rooster", bg: '#f3ced3', emoji: ["🐓"]},
    {name: "duck", bg: '#654e0b', emoji: ["🦆"]},
    {name: "goose", bg: '#8e6739', emoji: ["🪿"]},
    {name: "rabbit", bg: '#666666', emoji: ["🐰", "🐇"]},
    {name: "mouse", bg: '#5c5c5c', emoji: ["🐭", "🐁"]},
    {name: "rat", bg: '#1f1f1f', emoji: ["🐀"]},
    {name: "lion", bg: '#553d11', emoji: ["🦁"]},
    {name: "tiger", bg: '#65350b', emoji: ["🐯", "🐅"]},
    {name: "bear", bg: '#3d2714', emoji: ["🐻"]},
    {name: "polar bear", bg: '#add6d8', emoji: ["🐻‍❄️"]},
    {name: "panda", bg: '#5c5c5c', emoji: ["🐼"]},
    {name: "koala", bg: '#4d4d4d', emoji: ["🐨"]},
    {name: "monkey", bg: '#3b2816', emoji: ["🐵", "🐒"]},
    {name: "elephant", bg: '#5c5c5c', emoji: ["🐘"]},
    {name: "giraffe", bg: '#604610', emoji: ["🦒"]},
    {name: "zebra", bg: '#424242', emoji: ["🦓"]},
    {name: "deer", bg: '#704829', emoji: ["🦌"]},
    {name: "fox", bg: '#883e11', emoji: ["🦊"]},
    {name: "wolf", bg: '#405177', emoji: ["🐺"]},
    {name: "frog", bg: '#246a29', emoji: ["🐸"]},
    {name: "crocodile", bg: '#42541d', emoji: ["🐊"]},
    {name: "turtle", bg: '#2b5a36', emoji: ["🐢"]},
    {name: "dinosaur", bg: '#2c6337', emoji: ["🦖", "🦕"]},
    {name: "lizard", bg: '#4d9861', emoji: ["🦎"]},
    {name: "snake", bg: '#2b642e', emoji: ["🐍"]},
    {name: "snail", bg: '#37291b', emoji: ["🐌"]},
    {name: "fish", bg: '#0e5855', emoji: ["🐟", "🐠", "🐡"]},
    {name: "jellyfish", bg: '#f5e1f5', emoji: ["🪼"]},
    {name: "octopus", bg: '#7e1f8e', emoji: ["🐙"]},
    {name: "squid", bg: '#4e255f', emoji: ["🦑"]},
    {name: "lobster", bg: '#641e16', emoji: ["🦞"]},
    {name: "crab", bg: '#752710', emoji: ["🦀"]},
    {name: "whale", bg: '#1b5073', emoji: ["🐳", "🐋"]},
    {name: "dolphin", bg: '#21618c', emoji: ["🐬"]},
    {name: "shark", bg: '#39596a', emoji: ["🦈"]},
    {name: "shrimp", bg: '#d93f70', emoji: ["🦐"]},
    {name: "shell", bg: '#7095a8', emoji: ["🐚"]},
    {name: "coral", bg: '#d57b94', emoji: ["🪸"]},
    {name: "bug", bg: '#9ae11e', emoji: ["🐛", "🐞", "🦋", "🐜","🪲","🪰"]},
    {name: "butterfly", bg: '#f49ab5', emoji: ["🦋"]},
    {name: "caterpillar", bg: '#629b3c', emoji: ["🐛"]},
    {name: "ladybug", bg: '#f29ba2', emoji: ["🐞"]},
    {name: "bee", bg: '#f8ebbf', emoji: ["🐝"]},
    {name: "ant", bg: '#c39c79', emoji: ["🐜"]},
    {name: "fly", bg: '#c39c79', emoji: ["🪰"]},
    {name: "spider", bg: '#a3a3a3', emoji: ["🕷️","🕸️"]},
    {name: "beetle", bg: '#405e1c', emoji: ["🪲"]},
    {name: "grasshopper", bg: '#5f8336', emoji: ["🦗"]},
    {name: "worm", bg: '#764f29', emoji: ["🪱"]},
    {name: "bat", bg: '#2b2442', emoji: ["🦇"]},
    {name: "hedgehog", bg: '#4c3824', emoji: ["🦔"]},
    {name: "sloth", bg: '#6a5839', emoji: ["🦥"]},
    {name: "kangaroo", bg: '#785336', emoji: ["🦘"]},
    {name: "camel", bg: '#694c1b', emoji: ["🐫", "🐪"]},
    {name: "llama", bg: '#896824', emoji: ["🦙"]},
    {name: "squirrel", bg: '#784621', emoji: ["🐿️"]},
    {name: "raccoon", bg: '#525252', emoji: ["🦝"]},
    {name: "hippo", bg: '#c3cadf', emoji: ["🦛"]},
    {name: "rhino", bg: '#333333', emoji: ["🦏"]},
    {name: "gorilla", bg: '#242424', emoji: ["🦍"]},
    {name: "seal", bg: '#525252', emoji: ["🦭"]},
    {name: "otter", bg: '#160f08', emoji: ["🦦"]},
    {name: "bird", bg: '#124d73', emoji: ["🐦", "🐤", "🦅"]},
    {name: "owl", bg: '#4c3824', emoji: ["🦉"]},
    {name: "peacock", bg: '#0d635a', emoji: ["🦚"]},
    {name: "turkey", bg: '#e0a990', emoji: ["🦃"]},
    {name: "parrot", bg: '#104c20', emoji: ["🦜"]},
    {name: "swan", bg: '#757575', emoji: ["🦢"]},
    {name: "flamingo", bg: '#9c1144', emoji: ["🦩"]},
    {name: "penguin", bg: '#74cad3', emoji: ["🐧"]},
    {name: "dove", bg: '#6b6b6b', emoji: ["🕊️"]},
    // -- body parts --
    {name: "head", bg: '#eea363', emoji: ["🗣️"]},
    {name: "eyes", bg: '#0d5777', emoji: ["👀"]},
    {name: "ears", bg: '#9c6411', emoji: ["👂"]},
    {name: "nose", bg: '#c13f15', emoji: ["👃"]},
    {name: "mouth", bg: '#fce4e3', emoji: ["👄"]},
    {name: "teeth", bg: '#757575', emoji: ["🦷"]},
    {name: "tongue", bg: '#f6acc5', emoji: ["👅"]},
    {name: "shoulders", bg: '#6a4639', emoji: ["🤷"]},
    {name: "arms", bg: '#935e10', emoji: ["💪"]},
    {name: "hands", bg: '#81640e', emoji: ["🖐️", "✋"]},
    {name: "fingers", bg: '#776c0d', emoji: ["🤞", "👆"]},
    {name: "thumb", bg: '#327135', emoji: ["👍"]},
    {name: "legs", bg: '#146fb8', emoji: ["🦵"]},
    {name: "knees", bg: '#5665be', emoji: ["🦵"]},
    {name: "toes", bg: '#aa44bb', emoji: ["🦶"]},
    {name: "feet", bg: '#1c7d74', emoji: ["🦶"]},
    {name: "brain", bg: '#a51244', emoji: ["🧠"]},
    {name: "bones", bg: '#4f7792', emoji: ["🦴"]},
    // -- food --
    {name: "candy", bg: '#810e45', emoji: ["🍬", "🍭"]},
    {name: "cake", bg: '#d3185f', emoji: ["🎂", "🍰"]},
    {name: "pizza", bg: '#be3822', emoji: ["🍕"]},
    {name: "apple", bg: '#91121c', emoji: ["🍎", "🍏"]},
    {name: "banana", bg: '#81670e', emoji: ["🍌"]},
    {name: "grape", bg: '#1d052e', emoji: ["🍇"]},
    {name: "watermelon", bg: '#fce3ea', emoji: ["🍉"]},
    {name: "strawberry", bg: '#f8c9ca', emoji: ["🍓"]},
    {name: "lemon", bg: '#81740e', emoji: ["🍋"]},
    {name: "pineapple", bg: '#815d0e', emoji: ["🍍"]},
    {name: "mango", bg: '#9c4811', emoji: ["🥭"]},
    {name: "peach", bg: '#8a370f', emoji: ["🍑"]},
    {name: "coconut", bg: '#694125', emoji: ["🥥"]},
    {name: "corn", bg: '#5c4e0a', emoji: ["🌽"]},
    {name: "carrot", bg: '#814d0e', emoji: ["🥕"]},
    {name: "potato", bg: '#735530', emoji: ["🥔"]},
    {name: "tomato", bg: '#671313', emoji: ["🍅"]},
    {name: "bread", bg: '#755224', emoji: ["🍞"]},
    {name: "cheese", bg: '#937210', emoji: ["🧀"]},
    {name: "egg", bg: '#5f4c1b', emoji: ["🥚"]},
    {name: "bacon", bg: '#94242c', emoji: ["🥓"]},
    {name: "burger", bg: '#6d4722', emoji: ["🍔"]},
    {name: "hot dog", bg: '#923a25', emoji: ["🌭"]},
    {name: "taco", bg: '#80520f', emoji: ["🌮"]},
    {name: "burrito", bg: '#815f22', emoji: ["🌯"]},
    {name: "sushi", bg: '#862837', emoji: ["🍣"]},
    {name: "noodles", bg: '#f6e6ac', emoji: ["🍜"]},
    {name: "rice", bg: '#494927', emoji: ["🍚"]},
    {name: "popcorn", bg: '#5c4f0a', emoji: ["🍿"]},
    {name: "donut", bg: '#fad1dd', emoji: ["🍩"]},
    {name: "cookie", bg: '#6f4b2a', emoji: ["🍪"]},
    {name: "ice cream", bg: '#ca1651', emoji: ["🍦", "🍨"]},
    {name: "honey", bg: '#fae9d1', emoji: ["🍯"]},
    {name: "milk", bg: '#7e7e44', emoji: ["🥛"]},
    {name: "coffee", bg: '#492d1d', emoji: ["☕"]},
    {name: "juice", bg: '#8a4a0f', emoji: ["🧃"]},
    {name: "pretzel", bg: '#664629', emoji: ["🥨"]},
    {name: "pancake", bg: '#704815', emoji: ["🥞"]},
    {name: "waffle", bg: '#785217', emoji: ["🧇"]},
    {name: "soup", bg: '#743c11', emoji: ["🍲"]},
    {name: "sandwich", bg: '#7a5a24', emoji: ["🥪"]},
    {name: "fries", bg: '#8a6a10', emoji: ["🍟"]},
    {name: "pie", bg: '#7d5424', emoji: ["🥧"]},
    {name: "cupcake", bg: '#b0185a', emoji: ["🧁"]},
    {name: "pudding", bg: '#7a5320', emoji: ["🍮"]},
    {name: "chocolate", bg: '#4a2a16', emoji: ["🍫"]},
    {name: "croissant", bg: '#7d5a1e', emoji: ["🥐"]},
    {name: "bagel", bg: '#6d4a22', emoji: ["🥯"]},
    {name: "butter", bg: '#8a7418', emoji: ["🧈"]},
    {name: "salt", bg: '#6e6e6e', emoji: ["🧂"]},
    {name: "curry", bg: '#8a5a10', emoji: ["🍛"]},
    {name: "dumpling", bg: '#7a6a3a', emoji: ["🥟"]},
    {name: "meat", bg: '#7a2418', emoji: ["🍖", "🥩"]},
    {name: "nuts", bg: '#6a4a24', emoji: ["🥜"]},
    {name: "tea", bg: '#3f5a24', emoji: ["🍵"]},
    {name: "drink", bg: '#8a3a1e', emoji: ["🥤"]},
    // -- vegetables --
    {name: "broccoli", bg: '#1f4a1f', emoji: ["🥦"]},
    {name: "cucumber", bg: '#25501f', emoji: ["🥒"]},
    {name: "lettuce", bg: '#2f5d24', emoji: ["🥬"]},
    {name: "pepper", bg: '#7a1414', emoji: ["🫑", "🌶️"]},
    {name: "onion", bg: '#7d6a48', emoji: ["🧅"]},
    {name: "garlic", bg: '#6e6355', emoji: ["🧄"]},
    {name: "eggplant", bg: '#3c1f52', emoji: ["🍆"]},
    {name: "avocado", bg: '#3f5320', emoji: ["🥑"]},
    {name: "peas", bg: '#2f6132', emoji: ["🫛"]},
    {name: "beans", bg: '#5a3b23', emoji: ["🫘"]},
    {name: "olive", bg: '#4a5321', emoji: ["🫒"]},
    {name: "ginger", bg: '#8a6a34', emoji: ["🫚"]},
    {name: "yam", bg: '#8a4a20', emoji: ["🍠"]},
    {name: "pumpkin", bg: '#8f4a10', emoji: ["🎃"]},
    {name: "salad", bg: '#315a24', emoji: ["🥗"]},
    // -- more fruit --
    {name: "orange", bg: '#8a4a0c', emoji: ["🍊"]},
    {name: "pear", bg: '#5f6420', emoji: ["🍐"]},
    {name: "cherry", bg: '#8a0f2c', emoji: ["🍒"]},
    {name: "kiwi", bg: '#4a5c1c', emoji: ["🥝"]},
    {name: "melon", bg: '#6d7a24', emoji: ["🍈"]},
    {name: "blueberry", bg: '#26306e', emoji: ["🫐"]},
    // -- nature & weather --
    {name: "rain", bg: '#2f516a', emoji: ["🌧️", "☔", "💧"]},
    {name: "cloud", bg: '#3d82c2', emoji: ["☁️"]},
    {name: "snow", bg: '#1f5d84', emoji: ["❄️"]},
    {name: "snowman", bg: '#1c6192', emoji: ["⛄"]},
    {name: "storm", bg: '#95adc6', emoji: ["⛈️"]},
    {name: "lightning", bg: '#5c500a', emoji: ["⚡"]},
    {name: "fog", bg: '#6790ad', emoji: ["🌫️"]},
    {name: "umbrella", bg: '#0e212f', emoji: ["☔"]},
    {name: "sun", bg: '#6e520c', emoji: ["☀️", "🌞"]},
    {name: "moon", bg: '#15203c', emoji: ["🌙", "🌛"]},
    {name: "star", bg: '#2b2d6e', emoji: ["⭐", "🌟", "✨"]},
    {name: "fire", bg: '#933410', emoji: ["🔥"]},
    {name: "water", bg: '#15648c', emoji: ["💦"]},
    {name: "ice", bg: '#91dff9', emoji: ["🧊"]},
    {name: "stone", bg: '#8996aa', emoji: ["🪨"]},
    {name: "wind", bg: '#c5cdde', emoji: ["💨"]},
    {name: "blow", bg: '#324c5d', emoji: ["🌬️"]},
    {name: "rainbow", bg: '#9c115d', emoji: ["🌈"]},
    {name: "bubble", bg: '#c084c2', emoji: ["🫧"]},
    {name: "mountain", bg: '#273849', emoji: ["⛰️", "🏔️"]},
    {name: "volcano", bg: '#ecb2ac', emoji: ["🌋"]},
    {name: "beach", bg: '#6f5116', emoji: ["🏖️"]},
    {name: "wave", bg: '#16576f', emoji: ["🌊"]},
    {name: "island", bg: '#194d44', emoji: ["🏝️"]},
    {name: "tree", bg: '#1b4b1e', emoji: ["🌳", "🌲", "🌴"]},
    {name: "flower", bg: '#ae1351', emoji: ["🌸", "🌼", "🌻"]},
    {name: "leaf", bg: '#1c401d', emoji: ["🍃", "🍁"]},
    {name: "tulip", bg: '#721334', emoji: ["🌷"]},
    {name: "clover", bg: '#1cc41f', emoji: ["☘️"]},
    {name: "sunflower", bg: '#cba639', emoji: ["🌻"]},
    {name: "cactus", bg: '#285c2a', emoji: ["🌵"]},
    {name: "mushroom", bg: '#8a340f', emoji: ["🍄"]},
    // -- space --
    {name: "earth", bg: '#225959', emoji: ["🌍", "🌎", "🌏"]},
    {name: "planet", bg: '#3a295c', emoji: ["🪐"]},
    {name: "comet", bg: '#165a83', emoji: ["☄️"]},
    {name: "rocket", bg: '#192642', emoji: ["🚀"]},
    {name: "astronaut", bg: '#405c77', emoji: ["👨‍🚀"]},
    {name: "satellite", bg: '#414349', emoji: ["🛰️"]},
    {name: "alien", bg: '#115f2e', emoji: ["👽"]},
    // -- fantasy --
    {name: "unicorn", bg: '#7817d3', emoji: ["🦄"]},
    {name: "robot", bg: '#2e4456', emoji: ["🤖"]},
    {name: "monster", bg: '#2a1a40', emoji: ["👹", "👾"]},
    {name: "ghost", bg: '#5b5167', emoji: ["👻"]},
    {name: "dragon", bg: '#1e5a2a', emoji: ["🐉", "🐲"]},
    {name: "fairy", bg: '#6a2a7a', emoji: ["🧚‍♀️"]},
    {name: "mermaid", bg: '#1e5a6a', emoji: ["🧜‍♀️"]},
    {name: "wizard", bg: '#2a2a6a', emoji: ["🧙"]},
    {name: "superhero", bg: '#8a1e2a', emoji: ["🦸"]},
    {name: "genie", bg: '#4a2a7a', emoji: ["🧞"]},
    {name: "troll", bg: '#3a5a2a', emoji: ["🧌"]},
    {name: "elf", bg: '#2a5a3a', emoji: ["🧝"]},
    {name: "crystal", bg: '#4a1e6a', emoji: ["🔮"]},
    // -- vehicles --
    {name: "plane", bg: '#0c4f6e', emoji: ["✈️", "🛫"]},
    {name: "train", bg: '#1d2935', emoji: ["🚂", "🚆"]},
    {name: "car", bg: '#741010', emoji: ["🚗", "🚙", "🚕"]},
    {name: "bus", bg: '#65500b', emoji: ["🚌"]},
    {name: "truck", bg: '#85281e', emoji: ["🚚"]},
    {name: "motorcycle", bg: '#1a1a1a', emoji: ["🏍️"]},
    {name: "boat", bg: '#25597e', emoji: ["⛵"]},
    {name: "ship", bg: '#1c3c5f', emoji: ["🚢"]},
    {name: "helicopter", bg: '#32565d', emoji: ["🚁"]},
    {name: "taxi", bg: '#65500b', emoji: ["🚕"]},
    {name: "ambulance", bg: '#91121c', emoji: ["🚑"]},
    {name: "fire truck", bg: '#5f1212', emoji: ["🚒"]},
    {name: "tractor", bg: '#233b16', emoji: ["🚜"]},
    {name: "bicycle", bg: '#11554e', emoji: ["🚲"]},
    {name: "bike", bg: '#0c3c37', emoji: ["🚴"]},
    {name: "race car", bg: '#8a1010', emoji: ["🏎️"]},
    {name: "police", bg: '#1a3a6a', emoji: ["🚓"]},
    {name: "scooter", bg: '#2a5a6a', emoji: ["🛴"]},
    {name: "skateboard", bg: '#5a2a6a', emoji: ["🛹"]},
    {name: "van", bg: '#4a4a2a', emoji: ["🚐"]},
    {name: "subway", bg: '#2a2a3a', emoji: ["🚇"]},
    {name: "sled", bg: '#2a5a7a', emoji: ["🛷"]},
    {name: "canoe", bg: '#1e5a5a', emoji: ["🛶"]},
    // -- places --
    {name: "house", bg: '#6a3525', emoji: ["🏠", "🏡"]},
    {name: "castle", bg: '#405377', emoji: ["🏰"]},
    {name: "school", bg: '#923b30', emoji: ["🏫"]},
    {name: "hospital", bg: '#a3151f', emoji: ["🏥"]},
    {name: "tent", bg: '#2b5033', emoji: ["⛺"]},
    {name: "bridge", bg: '#a9c1d1', emoji: ["🌉"]},
    // -- objects --
    {name: "ball", bg: '#65380b', emoji: ["⚽", "🏀", "🎾"]},
    {name: "book", bg: '#845629', emoji: ["📚", "📖"]},
    {name: "rock", bg: '#8996aa', emoji: ["🪨"]},
    {name: "paper", bg: '#b9bdc0', emoji: ["📄"]},
    {name: "scissors", bg: '#7d8585', emoji: ["✂️"]},
    {name: "pencil", bg: '#6b4f10', emoji: ["✏️"]},
    {name: "hammer", bg: '#2e4256', emoji: ["🔨"]},
    {name: "lock", bg: '#405c77', emoji: ["🔒"]},
    {name: "key", bg: '#81610e', emoji: ["🔑"]},
    {name: "clock", bg: '#754f2e', emoji: ["⏰", "🕓"]},
    {name: "phone", bg: '#0e121b', emoji: ["📱"]},
    {name: "camera", bg: '#292929', emoji: ["📷"]},
    {name: "computer", bg: '#405c77', emoji: ["💻"]},
    {name: "light bulb", bg: '#8a710f', emoji: ["💡"]},
    {name: "gift", bg: '#91121c', emoji: ["🎁"]},
    {name: "balloon", bg: '#f7b6b6', emoji: ["🎈"]},
    {name: "kite", bg: '#18658b', emoji: ["🪁"]},
    {name: "music", bg: '#401763', emoji: ["🎵", "🎶", "🎸"]},
    {name: "piano", bg: '#292929', emoji: ["🎹"]},
    {name: "guitar", bg: '#731515', emoji: ["🎸"]},
    {name: "trumpet", bg: '#756d37', emoji: ["🎺"]},
    {name: "drum", bg: '#a5281c', emoji: ["🥁"]},
    {name: "crown", bg: '#8b771e', emoji: ["👑"]},
    {name: "gem", bg: '#0b514a', emoji: ["💎"]},
    {name: "ring", bg: '#6e5b0c', emoji: ["💍"]},
    {name: "glasses", bg: '#364c63', emoji: ["👓"]},
    {name: "hat", bg: '#8199c5', emoji: ["🎩"]},
    {name: "shoe", bg: '#694125', emoji: ["👟"]},
    {name: "backpack", bg: '#3a9e5f', emoji: ["🎒"]},
    {name: "magnet", bg: '#833a3a', emoji: ["🧲"]},
    {name: "target", bg: '#415c6b', emoji: ["🎯"]},
    {name: "trophy", bg: '#5c4b0a', emoji: ["🏆"]},
    {name: "medal", bg: '#5c4b0a', emoji: ["🏅"]},
    {name: "flag", bg: '#891a1a', emoji: ["🚩"]},
    {name: "map", bg: '#604925', emoji: ["🗺️"]},
    {name: "compass", bg: '#7c5e1d', emoji: ["🧭"]},
    {name: "puzzle", bg: '#7c53ac', emoji: ["🧩"]},
    {name: "dice", bg: '#c62525', emoji: ["🎲"]},
    {name: "teddy", bg: '#7a4a24', emoji: ["🧸"]},
    {name: "bell", bg: '#8a6a12', emoji: ["🔔"]},
    {name: "pen", bg: '#1f3a5c', emoji: ["🖊️"]},
    {name: "brush", bg: '#5c3a7a', emoji: ["🖌️"]},
    {name: "crayon", bg: '#a5451e', emoji: ["🖍️"]},
    {name: "paint", bg: '#6a2a6a', emoji: ["🎨"]},
    {name: "cart", bg: '#2e5c7a', emoji: ["🛒"]},
    {name: "basket", bg: '#7a5a2a', emoji: ["🧺"]},
    {name: "money", bg: '#1e5c3a', emoji: ["💰", "💵", "🪙"]},
    {name: "coin", bg: '#7a6218', emoji: ["🪙"]},
    {name: "trash", bg: '#3a4a52', emoji: ["🗑️"]},
    {name: "envelope", bg: '#5c6a7a', emoji: ["✉️"]},
    {name: "candle", bg: '#7a5a10', emoji: ["🕯️"]},
    {name: "yoyo", bg: '#a51e5a', emoji: ["🪀"]},
    {name: "slide", bg: '#1e6a7a', emoji: ["🛝"]},
    {name: "wand", bg: '#3a2a6a', emoji: ["🪄"]},
    {name: "battery", bg: '#2a5c2a', emoji: ["🔋"]},
    {name: "flashlight", bg: '#5c4a10', emoji: ["🔦"]},
    {name: "television", bg: '#25303a', emoji: ["📺"]},
    {name: "radio", bg: '#4a3a2a', emoji: ["📻"]},
    {name: "headphones", bg: '#2a2a3a', emoji: ["🎧"]},
    {name: "microphone", bg: '#4a2a4a', emoji: ["🎤"]},
    {name: "violin", bg: '#6a3a18', emoji: ["🎻"]},
    {name: "newspaper", bg: '#6a6a62', emoji: ["📰"]},
    {name: "calendar", bg: '#7a3a3a', emoji: ["📅"]},
    // -- tools --
    {name: "wrench", bg: '#3a4a5c', emoji: ["🔧"]},
    {name: "screwdriver", bg: '#4a3a2a', emoji: ["🪛"]},
    {name: "saw", bg: '#5c4a3a', emoji: ["🪚"]},
    {name: "axe", bg: '#5c3a2a', emoji: ["🪓"]},
    {name: "shovel", bg: '#4a4a3a', emoji: ["🪏", "⛏️"]},
    {name: "toolbox", bg: '#7a2a1e', emoji: ["🧰", "🛠️"]},
    {name: "ruler", bg: '#7a6a2a', emoji: ["📏", "📐"]},
    {name: "gear", bg: '#4a4a52', emoji: ["⚙️"]},
    {name: "rope", bg: '#6a5a3a', emoji: ["🪢"]},
    {name: "chain", bg: '#4a5259', emoji: ["⛓️"]},
    // -- bathroom & cleaning --
    {name: "toilet", bg: '#3a6a7a', emoji: ["🚽"]},
    {name: "toilet paper", bg: '#6a6a72', emoji: ["🧻"]},
    {name: "bathtub", bg: '#2a6a8a', emoji: ["🛁"]},
    {name: "shower", bg: '#2a5c7a', emoji: ["🚿"]},
    {name: "soap", bg: '#3a7a8a', emoji: ["🧼"]},
    {name: "sponge", bg: '#7a6a1e', emoji: ["🧽"]},
    {name: "toothbrush", bg: '#2a7a6a', emoji: ["🪥"]},
    {name: "broom", bg: '#6a4a2a', emoji: ["🧹"]},
    {name: "bucket", bg: '#3a5a7a', emoji: ["🪣"]},
    {name: "lotion", bg: '#7a5a5a', emoji: ["🧴"]},
    // -- clothing --
    {name: "shirt", bg: '#2a5c8a', emoji: ["👕"]},
    {name: "pants", bg: '#2a3a6a', emoji: ["👖"]},
    {name: "shorts", bg: '#3a5a8a', emoji: ["🩳"]},
    {name: "socks", bg: '#6a3a5a', emoji: ["🧦"]},
    {name: "scarf", bg: '#8a2a3a', emoji: ["🧣"]},
    {name: "cap", bg: '#2a5a3a', emoji: ["🧢"]},
    {name: "dress", bg: '#8a2a5a', emoji: ["👗"]},
    {name: "coat", bg: '#4a3a2a', emoji: ["🧥"]},
    {name: "gloves", bg: '#5a2a2a', emoji: ["🧤"]},
    {name: "boot", bg: '#4a2a1e', emoji: ["👢"]},
    {name: "sandal", bg: '#7a5a2a', emoji: ["🩴"]},
    {name: "swimsuit", bg: '#7a2a4a', emoji: ["🩱"]},
    {name: "tie", bg: '#2a2a4a', emoji: ["👔"]},
    {name: "purse", bg: '#6a2a4a', emoji: ["👜"]},
    // -- directions --
    {name: "up", bg: '#2a5c3a', emoji: ["⬆️"]},
    {name: "down", bg: '#5c2a2a', emoji: ["⬇️"]},
    {name: "left", bg: '#2a3a5c', emoji: ["⬅️"]},
    {name: "right", bg: '#5c4a1e', emoji: ["➡️"]},
    {name: "arrow", bg: '#3a3a4a', emoji: ["⬆️", "➡️", "⬇️", "⬅️"]},
    // -- sports & actions --
    {name: "soccer", bg: '#1e5c28', emoji: ["⚽"]},
    {name: "basketball", bg: '#5b2f0b', emoji: ["🏀"]},
    {name: "baseball", bg: '#7a6629', emoji: ["⚾"]},
    {name: "football", bg: '#3c2315', emoji: ["🏈"]},
    {name: "tennis", bg: '#3d4c10', emoji: ["🎾"]},
    {name: "golf", bg: '#285228', emoji: ["⛳"]},
    {name: "swim", bg: '#135253', emoji: ["🏊"]},
    {name: "skate", bg: '#1e5d71', emoji: ["⛸️"]},
    {name: "ski", bg: '#0b4165', emoji: ["⛷️"]},
    {name: "surf", bg: '#104d61', emoji: ["🏄"]},
    {name: "bowling", bg: '#2d3c58', emoji: ["🎳"]},
    // -- emotions & face --
    {name: "hello", bg: '#23a7f9', emoji: ["🖐️"]},
    {name: "happy", bg: '#6897ca', emoji: ["😀", "😄", "🎉"]},
    {name: "sad", bg: '#404367', emoji: ["😢", "😭"]},
    {name: "scared", bg: '#503075', emoji: ["😱"]},
    {name: "laugh", bg: '#4b8cca', emoji: ["😂", "🤣"]},
    {name: "smile", bg: '#ffef07', emoji: ["😊"]},
    {name: "angry", bg: '#9b1d1d', emoji: ["😠", "😡"]},
    {name: "sleepy", bg: '#644f92', emoji: ["😴"]},
    {name: "party", bg: '#6b168d', emoji: ["🎉", "🎊", "🥳"]},
    {name: "cool", bg: '#c8eaf9', emoji: ["😎"]},
    {name: "wink", bg: '#ae1349', emoji: ["😉"]},
    {name: "silly", bg: '#a5125b', emoji: ["🤪"]},
    {name: "love", bg: '#770d34', emoji: ["❤️", "💕", "😍"]},
    {name: "kiss", bg: '#a5123b', emoji: ["😘"]},
    // -- buildings & property --
    {name: "building", bg: '#394e6a', emoji: ["🏢", "🏬", "🏛️"]},
    {name: "skyscraper", bg: '#365063', emoji: ["🏙️", "🏢"]},
    {name: "property", bg: '#534227', emoji: ["🏘️", "🏠", "🏡"]},
    {name: "city", bg: '#1f1d35', emoji: ["🏙️", "🌆", "🌃"]},
    {name: "town", bg: '#404927', emoji: ["🏘️", "🏡"]},
    {name: "village", bg: '#423724', emoji: ["🛖", "🏘️"]},
    {name: "hut", bg: '#302518', emoji: ["🛖"]},
    {name: "store", bg: '#7e1b1b', emoji: ["🏪", "🏬"]},
    {name: "bank", bg: '#1e523c', emoji: ["🏦"]},
    {name: "hotel", bg: '#1a5d75', emoji: ["🏨"]},
    {name: "factory", bg: '#474747', emoji: ["🏭"]},
    {name: "office", bg: '#3d5771', emoji: ["🏢"]},
    {name: "stadium", bg: '#1a4222', emoji: ["🏟️"]},
    {name: "tower", bg: '#7d251c', emoji: ["🗼"]},
    {name: "construction", bg: '#fbeedb', emoji: ["🏗️", "🚧"]},
    {name: "brick", bg: '#833521', emoji: ["🧱"]},
    {name: "wall", bg: '#64402b', emoji: ["🧱"]},
    {name: "door", bg: '#5f4025', emoji: ["🚪"]},
    {name: "window", bg: '#2d6c9f', emoji: ["🪟"]},
    {name: "ladder", bg: '#d4a354', emoji: ["🪜"]},
    {name: "museum", bg: '#50432b', emoji: ["🏛️"]},
    {name: "library", bg: '#694125', emoji: ["📚", "🏛️"]},
    {name: "mailbox", bg: '#143252', emoji: ["📫", "📮"]},
    {name: "fountain", bg: '#18658b', emoji: ["⛲"]},
    {name: "statue", bg: '#2e564e', emoji: ["🗽", "🗿"]},
    {name: "bed", bg: '#b19cc9', emoji: ["🛏️"]},
    {name: "chair", bg: '#cfb196', emoji: ["🪑"]},
    {name: "couch", bg: '#3e325d', emoji: ["🛋️"]},
    {name: "mirror", bg: '#4b7a96', emoji: ["🪞"]},
    {name: "elevator", bg: '#3d5771', emoji: ["🛗"]},
    {name: "farm", bg: '#31480a', emoji: ["🚜", "🌾", "🏡"]},
    {name: "garden", bg: '#224e24', emoji: ["🌷", "🌻", "🌱"]},
];

// Other words that should land on an existing keyword: nicknames, regional
// spellings, and the everyday word when the table stores a different one.
// Written alias -> keyword, and merged into the same lookup the keyword
// names go into (see buildLookup in matching.js), so aliases get plural
// handling for free - "puppies" finds "puppy" finds "dog".
//
// An alias may not name a real keyword (a keyword always wins) and may not
// point at another alias; validateTables() enforces both at startup.
//
// Multi-word names and aliases DO work - write them with single spaces, as
// "polar bear" does above. The matcher rejoins adjacent typed words to find
// them, longest phrase first, so "polar bear" wins over the "bear" inside it
// and consumes both words. Only the last word of a phrase gets plural/-ing
// handling, which is what makes "polar bears" land on "polar bear". The one
// hard rule is that a name or alias must be spellable by typing: lowercase
// a-z words, single-spaced, nothing else - no hyphens, apostrophes or
// digits, since tokenizing throws those away and the key could never be hit.
const keywordAliases = {
    // -- animals --
    puppy: "dog", pup: "dog", doggy: "dog", puppydog: "dog",
    kitty: "cat", kitten: "cat", bunny: "rabbit", piggy: "pig",
    birdie: "bird", horsey: "horse", pony: "horse", ducky: "duck", joey: "kangaroo",
    polarbear: "polar bear", iceberg: "polar bear",
    "puppy dog": "dog",
    // -- run-together spellings of the multi-word keywords --
    // Every name that reads as two words is stored that way, and the spelling
    // with the space closed up is kept here. These were the actual names
    // before multi-word keywords existed, so the aliases are what stop older
    // muscle memory - and a child who simply doesn't put the space in - from
    // suddenly matching nothing.
    hotdog: "hot dog", icecream: "ice cream", lightbulb: "light bulb",
    firetruck: "fire truck", racecar: "race car", toiletpaper: "toilet paper",
    // -- vehicles --
    auto: "car", automobile: "car", airplane: "plane", aeroplane: "plane",
    jet: "plane", lorry: "truck", cycle: "bicycle", sailboat: "boat",
    chopper: "helicopter", race: "race car", racing: "race car",
    policecar: "police", "police car": "police", minivan: "van", metro: "subway",
    sledge: "sled", toboggan: "sled", kayak: "canoe",
    // -- fantasy --
    pixie: "fairy", witch: "wizard", magician: "wizard", hero: "superhero",
    // -- food --
    sweets: "candy", lollipop: "candy", lolly: "candy",
    hamburger: "burger", cheeseburger: "burger",
    pasta: "noodles", spaghetti: "noodles", biscuit: "cookie",
    birthday: "cake", chips: "fries", peanut: "nuts", steak: "meat",
    beef: "meat", soda: "drink", pop: "drink", cola: "drink", berry: "blueberry",
    aubergine: "eggplant", zucchini: "cucumber", courgette: "cucumber",
    capsicum: "pepper", chilli: "pepper", chili: "pepper",
    cabbage: "lettuce", jackolantern: "pumpkin", "jack o lantern": "pumpkin",
    // -- nature & weather --
    sea: "water", ocean: "wave", tornado: "storm", twister: "storm",
    thunder: "lightning", blossom: "flower",
    // -- space --
    spaceman: "astronaut", cosmonaut: "astronaut", ufo: "alien",
    // -- objects --
    mobile: "phone", cellphone: "phone", "cell phone": "phone",
    laptop: "computer", pc: "computer",
    present: "gift", specs: "glasses", spectacles: "glasses",
    sneaker: "shoe", trainer: "shoe", jewel: "gem",
    photo: "camera", watch: "clock", bulb: "light bulb",
    // `cap` used to point at "hat" and now can't: it is a keyword of its own
    // (the billed cap), and a keyword always beats an alias, so leaving the
    // alias here would fail validateTables() at startup rather than being
    // quietly ignored.
    teddybear: "teddy", "teddy bear": "teddy", paintbrush: "brush", marker: "pen",
    spade: "shovel", tools: "toolbox", torch: "flashlight",
    cash: "money", dollar: "money", garbage: "trash", rubbish: "trash",
    bin: "trash", trolley: "cart", wagon: "cart", letter: "envelope",
    news: "newspaper", fiddle: "violin", mic: "microphone",
    tv: "television", telly: "television", playground: "slide",
    handbag: "purse", magic: "wand",
    // -- tools, bathroom & cleaning --
    potty: "toilet", loo: "toilet", restroom: "toilet", bathroom: "toilet",
    tub: "bathtub", bath: "bathtub",
    // -- clothing --
    // "t shirt" also catches "t-shirt": tokenizing drops the hyphen and
    // leaves the same two words.
    trousers: "pants", jeans: "pants", tshirt: "shirt", "t shirt": "shirt",
    jacket: "coat",
    gown: "dress", mitten: "gloves",
    // -- emotions & face --
    lol: "laugh", funny: "laugh", mad: "angry", tired: "sleepy", cry: "sad", grin: "smile", friend: "smile",
    // -- shapes, fantasy, sports --
    box: "square", zombie: "monster", hoops: "basketball",
    // -- buildings & property --
    home: "house", cottage: "house", mansion: "house",
    apartment: "building", highrise: "skyscraper", "high rise": "skyscraper",
    estate: "property",
    downtown: "city", neighborhood: "town", cabin: "hut", shed: "hut",
    shop: "store", market: "store", mall: "store",
    inn: "hotel", motel: "hotel", palace: "castle", fort: "castle", camp: "tent",
    crane: "construction", gate: "door", lift: "elevator", sofa: "couch",
    monument: "statue", sculpture: "statue",
    mail: "mailbox", letterbox: "mailbox", postbox: "mailbox",
    barn: "farm", ranch: "farm", yard: "garden", backyard: "garden",
    // -- verbs whose -ing form has no keyword to strip back to --
    // "golfing", "skating", "swimming" and the rest need nothing here:
    // wordVariants() strips -ing (undoubling consonants and restoring a
    // dropped -e) and finds golf / skate / swim on its own. These are only
    // the ones where the bare verb isn't a keyword, so there's nothing for
    // the rule to land on and the action needs pointing at an object.
    sleeping: "sleepy", reading: "book", writing: "pencil",
    drawing: "pencil", painting: "brush", driving: "car",
    flying: "plane", sailing: "boat", climbing: "mountain",
    baking: "cake", cooking: "soup", burning: "fire",
    singing: "music", dancing: "party", eating: "burger",
    running: "shoe", jumping: "frog", digging: "shovel",
    fixing: "hammer", ringing: "clock", swinging: "kite",
    raking: "leaf",
    shining: "sun", melting: "ice", floating: "bubble",
    exploding: "volcano",
};
